changelog:
  exclude:
    labels:
      - "autorelease: pending"
      - "autorelease: tagged"
      - "autorelease: snapshot"
  categories:
    - title: 🚀 Features
      labels:
        - "type: feature request"
        - "commit: feat"
    - title: 🐛 Bug Fixes
      labels:
        - "type: bug"
        - "commit: fix"
    - title: 📚 Documentation
      labels:
        - "type: documentation"
        - "commit: docs"
    - title: 🔄 Enhancements
      labels:
        - "type: enhancement"
        - "commit: refactor"
        - "commit: perf"
    - title: 🧪 Tests
      labels:
        - "commit: test"
    - title: 🔧 Maintenance
      labels:
        - "commit: chore"
        - "commit: style"
    - title: 💥 Breaking Changes
      labels:
        - "breaking change"
    - title: Other Changes
      labels:
        - "*"