blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/lusu007/dienstplan/discussions
    about: Please ask and answer questions here.
  - name: Conventional Commits Guide
    url: https://www.conventionalcommits.org/
    about: Learn more about conventional commit format.

